server:
  port: 8084

spring:
  application:
    name: payment-service
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3307/paymentdb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate: { ddl-auto: validate }
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}

resilience4j:
  bulkhead:
    instances:
      stripe:
        max-concurrent-calls: 20
        max-wait-duration: 200ms
  retry:
    instances:
      stripe:
        max-attempts: 3
        wait-duration: 250ms
        exponential-backoff-multiplier: 2

management:
  endpoints:
    web:
      exposure: { include: health, info, prometheus, circuitbreakers }
  tracing:
    sampling: { probability: 1.0 }
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411/api/v2/spans}

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]"
